### ISSUE TITLE
Doesn't include animation module

### ISSUE THREAD

**Issue by daniel** [ryanswapp/fabricjs#1]
This package doesn't include the Fabric.js animation module.

**Comment by ryanswapp** [comment]
This package includes the complete version of Fabric 1.5 (full build from the website). What in particular do you believe is missing? Have you tried to animate a specific object and are getting an error?

**Comment by daniel** [comment]
Yes I got an error that animate was undefined. When I search for "animate" in https://github.com/ryanswapp/fabricjs/blob/master/client/fabric.min.js there are no matches. 

In the first line of the file you can see that the animation module is not included.

You can compare it with this file:
https://github.com/kangax/fabric.js/blob/master/dist/fabric.min.js

For some reason the animation module is not included on http://fabricjs.com/build/.

**Comment by ryanswapp** [comment]
Interesting. I hadn't needed the animation features so I didn't notice that it was missing. I just uploaded a new version of the package with the https://github.com/kangax/fabric.js/blob/master/dist/fabric.min.js file. Let me know if you have any more problems.

**Comment by daniel** [comment]
Thanks, it works fine now!
